### PR TITLE
Fix issues due to changes in `sanitize_sql` in ActiveRecord

### LINKED ISSUE #71: Error due to changes in `sanitize_sql`
`sanitize_sql` no longer accepts hashes as argument
https://github.com/rails/rails/pull/20121

### PR DESCRIPTION
**Pull request by thegeorgeous**
`sanitize_sql` no longer accepts hashes in Rails > 5

Fixes #71

### CODE REVIEW

**Comment by weber-s** [comment]
Hello!

Any news for this PR? Since the current packaged gem (1.1.1) has error, it would be realy nice to have this merge and release :)

**Comment by sreecodeslayer** [comment]
@thegeorgeous 
Changes looks good to me 🙂 
Should we be concerned about the numerous errors(not failures) in test?

**Comment by thegeorgeous** [comment]
@sreecodeslayer the errors are all related to changes in Rails 5. We will fix it in another PR.

**Comment by sreecodeslayer** [comment]
> @sreecodeslayer the errors are all related to changes in Rails 5. We will fix it in another PR.

Ah got it, makes sense. approving this one in that case 👍

**Pull request merged**
